version: '3.8'

services:
  db:
    image: mysql:8.0.34
    volumes:
      - db_data:/var/lib/mysql
      - ./db/create.sql:/docker-entrypoint-initdb.d/1.sql
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: thales_demo
      MYSQL_USER: user
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3306:3306"

  api:
    depends_on:
      - db
    image: jonip/transactions-api:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: ${DB_PASS}

volumes:
  db_data: