version: '3.8'

services:
  db:
    image: mysql:8.0.34
    volumes:
      - db_data:/var/lib/mysql
      - ./db/create.sql:/docker-entrypoint-initdb.d/1.sql
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: thales_demo
      MYSQL_USER: user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
        - db_root_password
        - db_password
    ports:
      - "3306:3306"

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt

volumes:
  db_data: